### PR TITLE
A Clean geodata branch that does not mess with existing migrations

### PR DESCRIPTION
**Pull request by PeteCoward**
The plan is to tag this commit with release 1.3 and push to pypi. We'll ensure LI and Tempu point to 1.2 so don't need attention, but can easily eventually upgrade by adding any required data in locally in their projects.

New Openly projects get a clean, new, empty simple locations with geodata files.
hamutuk may have to do some dancing with fake migrations to get back on the straight and narrow.

All ok? Anhy concerns?

**Edit**
Liga now does point to specifically 1.2
Tempu points to a specific commit

### CODE REVIEW

**Comment by PeteCoward** [comment]
I'm going to change this to neuter the loaddata migration, so it is there and will run, but won't do anything.

**Comment by syting** [comment]
This all looks fine to me. The one note I'd make is replacing unicode with str requires the projects be on python3. I believe liga-inan is our only project still on python2 and since it's not pointing at this version of simple-locations that should be fine.

**Comment by syting** [comment]
Although, since we're making breaking changes maybe this should be simple-locations 2.0 :)

**Review by raphaelmerx — COMMENTED** [review]
You can add the decorator [`@python_2_unicode_compatible`](https://docs.djangoproject.com/en/1.10/topics/python3/#str-and-unicode-methods) to your models to make them Python 2 and 3 compatible.

**Comment by PeteCoward** [comment]
Comments addressed

**Comment by raphaelmerx** [comment]
Nice! Basically the only things we have to do in Liga Inan to upgrade the simple_locations dependency are:
* adding a migration to load the initial data
* change the db engine to `django.contrib.gis.db.backends.postgis`

**Pull request merged**
