### PR TITLE
Modeltranslation+osm

### PR DESCRIPTION
**Pull request by joshbrooks**
This moves the admin basemap to OSM and adds model translation fields

 - Requires running the `sync_model_translations` command
 - Requires manually updating the `name_en` field with content of the `name` field for things to show up correctly

### CODE REVIEW

**Review by raphaelmerx — CHANGES_REQUESTED** [review]
- Not sure this should be on top of https://github.com/catalpainternational/simple_locations/pull/9, which has been left open  for a while. Maybe just merge the `modeltranslations` branch?
- The operations in `sync_translation_fields` should be inside a migration, so this command doesn't need to be run on all projectbank databases.
- We could also make the `name` -> `name_en` migration inside a data migration

**Comment by raphaelmerx** [comment]
Getting the following error when trying to access the admin for an area after running the migration:
```
formfield_for_dbfield() takes 2 positional arguments but 3 were given
```

**Comment by RobertoMaurizzi** [comment]
#9 has been left open because we were swamped. I'm currently using it in Liga Inan staging and training (and local) and it works.

**Comment by joshbrooks** [comment]
Related to https://github.com/catalpainternational/openly/pull/2456
@raphaelmerx Migration added to Openly in aims - it's a bit tricky to know where to put that one :smile:

**Comment by joshbrooks** [comment]
This is now on pypi as release 2.75.1

**Review by RobertoMaurizzi — APPROVED** [review]
Good for me/Liga Inan (on both Py2 and Py3 but with no translation needs)

**Pull request merged**
