### PR TITLE
Django 111

### PR DESCRIPTION
**Pull request by joshbrooks**

### CODE REVIEW

**Review by PeteCoward — APPROVED** [review]

**Comment by raphaelmerx** [comment]
How can I test this?

**Comment by raphaelmerx** [comment]
Oh apparently I'm not a reviewer anymore!

**Comment by PeteCoward** [comment]
I figured it was safe as all our projects use either pinned versions, or pypi pushes. It avoids exceptions running with django 111

**Comment by joshbrooks** [comment]
I think merging will do now harm

**Pull request merged**
